<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Models\Siswa;
use App\Models\Attendance;
use App\Models\MessageQueue;
use App\Models\Setting;
use App\Models\HariLibur;
use App\Models\Kelas;
use Carbon\Carbon;

class DailyReportCommand extends Command
{
    protected $signature = 'absen:daily-report {targetJid?}';
    protected $description = 'Generate daily attendance report and send to WhatsApp Group';

    public function handle()
    {
        $targetJid = $this->argument('targetJid');

        // Look up setting if not provided (legacy support)
        if (!$targetJid) {
            $targetJid = Setting::where('setting_key', 'report_target_jid')->value('setting_value');
        }

        // Get classes with WhatsApp Group ID
        $kelasWithGroupId = Kelas::whereNotNull('wa_group_id')
            ->where('wa_group_id', '!=', '')
            ->where('is_active_attendance', true)
            ->get();

        if ($kelasWithGroupId->isEmpty() && !$targetJid) {
            $this->error("No classes with WhatsApp Group ID and target JID not found in settings.");
            return;
        }

        $today = now()->format('Y-m-d');

        // CHECK 1: Sunday
        if (now()->isSunday()) {
            $this->info("Today is Sunday. Report Skipped.");
            return;
        }

        // CHECK 2: Holiday (Hari Libur)
        if (HariLibur::where('tanggal', $today)->exists()) {
            $this->info("Today is Holiday ($today). Report Skipped.");
            return;
        }

        // Debounce check
        $lastRun = Setting::where('setting_key', 'last_daily_report_date')->value('setting_value');
        if ($lastRun === $today) {
            $this->info("DailyReport already ran today ($today).");
            return;
        }

        $this->info("Generating report for $today...");

        $siswaAll = Siswa::whereHas('kelas', function ($q) {
            $q->where('is_active_attendance', true);
        })->orderBy('nama')->get();

        $attendance = Attendance::where('tanggal', $today)->get()->keyBy('student_id');

        $totalMasuk = 0;
        $totalTidakMasuk = 0;
        $listTidakMasuk = [];

        foreach ($siswaAll as $s) {
            if ($attendance->has($s->id)) {
                $att = $attendance[$s->id];
                if ($att->status === 'H') {
                    $totalMasuk++;
                } else {
                    $totalTidakMasuk++;
                    $statusKet = match ($att->status) {
                        'I' => 'Izin',
                        'S' => 'Sakit',
                        'A' => 'Alpha',
                        'B' => 'Bolos',
                        default => $att->status
                    };
                    $listTidakMasuk[] = "{$s->nama} ({$statusKet})";
                }
            } else {
                // No record = Alpha
                $totalTidakMasuk++;
                $listTidakMasuk[] = "{$s->nama} (Alpha)";
            }
        }

        // Format Message
        $msg = "📊 *Laporan Absensi Harian*\n";
        $msg .= "📅 Tanggal: " . now()->format('d/m/Y') . "\n";
        $msg .= "---------------------------\n";
        $msg .= "✅ Siswa Masuk: $totalMasuk\n";
        $msg .= "❌ Siswa Tidak Masuk: $totalTidakMasuk\n";
        $msg .= "---------------------------\n";

        if ($totalTidakMasuk > 0) {
            $msg .= "*Daftar Siswa Tidak Masuk:*\n";
            foreach ($listTidakMasuk as $item) {
                $msg .= "- $item\n";
            }
        } else {
            $msg .= "🎉 *Nihil (Semua Masuk)*\n";
        }

        $msg .= "\n_Generated by System_";

        // Queue Message to all classes with WhatsApp Group ID
        foreach ($kelasWithGroupId as $kelas) {
            MessageQueue::create([
                'phone_number' => $kelas->wa_group_id,
                'message' => $msg,
                'status' => 'pending',
                'created_at' => now()
            ]);
            $this->info("Queued global report to {$kelas->nama_kelas} group ({$kelas->wa_group_id})");
        }

        // Also send to legacy target if exists
        if ($targetJid) {
            MessageQueue::create([
                'phone_number' => $targetJid,
                'message' => $msg,
                'status' => 'pending',
                'created_at' => now()
            ]);
            $this->info("Queued global report to legacy target ({$targetJid})");
        }


        // --- NEW: Laporan Per Wali Kelas ---
        $this->info("Processing Wali Kelas reports...");

        $kelasWithWali = \App\Models\Kelas::whereNotNull('wali_kelas_id')->with('waliKelas')->get();
        $studentsByClass = $siswaAll->groupBy('kelas_id');

        foreach ($kelasWithWali as $kelas) {
            $wali = $kelas->waliKelas;

            // Skip if Wali Kelas has no phone number or no students
            if (!$wali || !$wali->no_wa || !isset($studentsByClass[$kelas->id])) {
                continue;
            }

            $siswaKelas = $studentsByClass[$kelas->id];
            $totalSiswa = $siswaKelas->count();

            $masuk = 0;
            $tidakMasuk = 0;
            $listAbsen = [];

            foreach ($siswaKelas as $s) {
                if ($attendance->has($s->id)) {
                    $att = $attendance[$s->id];
                    if ($att->status === 'H') {
                        $masuk++;
                    } else {
                        $tidakMasuk++;
                        $statusKet = match ($att->status) {
                            'I' => 'Izin',
                            'S' => 'Sakit',
                            'A' => 'Alpha',
                            'B' => 'Bolos',
                            default => $att->status
                        };
                        $listAbsen[] = "{$s->nama} ({$statusKet})";
                    }
                } else {
                    $tidakMasuk++;
                    $listAbsen[] = "{$s->nama} (Alpha)";
                }
            }

            // Only send if there are students (which we already checked)
            // Construct Message
            $msgWali = "📊 *Laporan Absensi Kelas {$kelas->nama_kelas}*\n";
            $msgWali .= "👤 Wali Kelas: {$wali->nama}\n";
            $msgWali .= "📅 Tanggal: " . now()->format('d/m/Y') . "\n";
            $msgWali .= "---------------------------\n";
            $msgWali .= "✅ Hadir: $masuk\n";
            $msgWali .= "❌ Tidak Hadir: $tidakMasuk\n";
            $msgWali .= "---------------------------\n";

            if ($tidakMasuk > 0) {
                $msgWali .= "*Detail Tidak Hadir:*\n";
                foreach ($listAbsen as $item) {
                    $msgWali .= "- $item\n";
                }
            } else {
                $msgWali .= "🎉 *Nihil (Semua Masuk)*\n";
            }

            $msgWali .= "\n_Generated by System_";

            // Queue Message
            MessageQueue::create([
                'phone_number' => $wali->no_wa,
                'message' => $msgWali,
                'status' => 'pending',
                'created_at' => now()
            ]);

            $this->info("Queued report for {$kelas->nama_kelas} -> {$wali->nama} ({$wali->no_wa})");
        }

        // Mark done
        Setting::updateOrCreate(
            ['setting_key' => 'last_daily_report_date'],
            ['setting_value' => $today]
        );
    }
}
