<?php
// cron/daily_report.php
// Script untuk generate laporan harian dan kirim ke Group WhatsApp via Queue

if (php_sapi_name() !== 'cli') {
    die("Access denied. CLI only.");
}

require_once __DIR__ . '/../includes/db.php';

// Ambil Target Group ID dari argument
$targetJid = $argv[1] ?? null;

if (!$targetJid) {
    die("Usage: php daily_report.php <whatsapp_group_id>\nExample: php daily_report.php 123456789-123456@g.us\n");
}

echo "Generating Daily Report for: $targetJid\n";
date_default_timezone_set('Asia/Jakarta');
$today = date('Y-m-d');

try {
    // 1. Ambil semua siswa aktif
    $stmt = $pdo->query("SELECT id, nama FROM siswa ORDER BY nama ASC");
    $allSiswa = $stmt->fetchAll(PDO::FETCH_ASSOC);
    
    // 2. Ambil absensi hari ini (dari tabel attendance, asumsi tabel utama log harian)
    // Note: Berdasarkan rfid.php, data masuk ke 'attendance'.
    $stmt = $pdo->prepare("SELECT student_id, status, keterangan FROM attendance WHERE tanggal = ?");
    $stmt->execute([$today]);
    $attendanceData = $stmt->fetchAll(PDO::FETCH_ASSOC);
    
    // Map attendance by student_id
    $attMap = [];
    foreach ($attendanceData as $row) {
        $attMap[$row['student_id']] = $row;
    }
    
    // 3. Kategorisasi
    $totalMasuk = 0;
    $totalTidakMasuk = 0;
    $listTidakMasuk = []; // Array of strings "Nama (Status)"
    
    foreach ($allSiswa as $siswa) {
        $sid = $siswa['id'];
        $nama = $siswa['nama'];
        
        if (isset($attMap[$sid])) {
            $status = $attMap[$sid]['status']; // H, I, S, A
            
            if ($status === 'H') {
                $totalMasuk++;
            } else {
                // I, S, A
                $totalTidakMasuk++;
                $ketStatus = match ($status) {
                    'I' => 'Izin',
                    'S' => 'Sakit',
                    'A' => 'Alpha',
                    default => $status
                };
                $listTidakMasuk[] = "$nama ($ketStatus)";
            }
        } else {
            // Tidak ada record = Alpha
            $totalTidakMasuk++;
            $listTidakMasuk[] = "$nama (Alpha)";
        }
    }
    
    // 4. Format Pesan
    $msg  = "📊 *Laporan Absensi Harian*\n";
    $msg .= "📅 Tanggal: " . date('d/m/Y') . "\n";
    $msg .= "---------------------------\n";
    $msg .= "✅ Siswa Masuk: $totalMasuk\n";
    $msg .= "❌ Siswa Tidak Masuk: $totalTidakMasuk\n";
    $msg .= "---------------------------\n";
    
    if ($totalTidakMasuk > 0) {
        $msg .= "*Daftar Siswa Tidak Masuk:*\n";
        foreach ($listTidakMasuk as $item) {
            $msg .= "- $item\n";
        }
    } else {
        $msg .= "🎉 *Nihil (Semua Masuk)*\n";
    }
    
    $msg .= "\n_Generated by System_";
    
    // 5. Insert ke Message Queue
    // Validasi format JID minimal
    if (!strpos($targetJid, '@')) {
        // Jika user lupa @g.us, kita asumsi dia kirim '123-456'
        // Tapi untuk amannya kita tidak auto-append kecuali user yakin.
        // Kita biarkan user input raw.
    }

    $stmt = $pdo->prepare("
        INSERT INTO message_queue (phone_number, message, status, created_at)
        VALUES (?, ?, 'pending', NOW())
    ");
    $stmt->execute([$targetJid, $msg]);
    
    echo "[SUCCESS] Laporan berhasil di-generate dan masuk antrian.\n";
    echo "Preview:\n$msg\n";

} catch (PDOException $e) {
    die("Database Error: " . $e->getMessage() . "\n");
}
